# Generated by Selenium IDE
import pytest
import time
from selenium import webdriver
from selenium.webdriver.common.by import By

class TestBrowserNavigation():

    def setup_method(self, method):
        self.driver = webdriver.Firefox()

    def teardown_method(self, method):
        self.driver.quit()

    def test_browser_navigation(self):
        # 1. Open browser and navigate
        self.driver.get("https://tutorialsninja.com/demo/")
        self.driver.maximize_window()
        print("Title after opening example.com:", self.driver.title)
        time.sleep(2)

        # 2. Navigate to another page on same site
        self.driver.get("https://tutorialsninja.com/demo/index.php?route=account/register")
        print("Title after navigating to second page:", self.driver.title)
        time.sleep(2)

        # 3. Use back()
        self.driver.back()
        print("Title after back():", self.driver.title)
        time.sleep(2)

        # 4. Use forward()
        self.driver.forward()
        print("Title after forward():", self.driver.title)
        time.sleep(2)

        # 5. Use refresh()
        self.driver.refresh()
        print("Title after refresh():", self.driver.title)
        time.sleep(2)

        self.driver.quit()
